server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://vm1.local:5432/security
    username: postgres
    password: root
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.milloc.security.service: DEBUG
    com.milloc.security.interceptor: DEBUG

